services:
  front-end:
    build:
      target: dev
    volumes:
      - ./:/workspace:cached
    ports:
      - "80:80"
    command: /bin/bash -c "while sleep 1000; do :; done"

  database:
    image: postgres:17.2
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
